# Generated by Django 4.1.3 on 2023-04-04 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choiceofmultiplechoicequestion',
            options={'verbose_name': 'Choice Of MultipleChoice Question', 'verbose_name_plural': 'Choices Of MultipleChoice Question'},
        ),
        migrations.AlterModelOptions(
            name='descriptiveanswer',
            options={'verbose_name': 'Descriptive Answer', 'verbose_name_plural': 'Descriptive Answers'},
        ),
        migrations.AlterModelOptions(
            name='exam',
            options={'verbose_name': 'Exam', 'verbose_name_plural': 'Exams'},
        ),
        migrations.AlterModelOptions(
            name='fileanswer',
            options={'verbose_name': 'File Answer', 'verbose_name_plural': 'File Answers'},
        ),
        migrations.AlterModelOptions(
            name='multiplechoiceanswer',
            options={'verbose_name': 'Multiple Choice Answer', 'verbose_name_plural': 'Multiple Choice Answers'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
        migrations.AlterModelOptions(
            name='userexam',
            options={'verbose_name': 'User Exam', 'verbose_name_plural': 'User Exams'},
        ),
        migrations.AlterField(
            model_name='choiceofmultiplechoicequestion',
            name='choice',
            field=models.CharField(max_length=200, verbose_name='choice'),
        ),
        migrations.AlterField(
            model_name='choiceofmultiplechoicequestion',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_date'),
        ),
        migrations.AlterField(
            model_name='choiceofmultiplechoicequestion',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='icon'),
        ),
        migrations.AlterField(
            model_name='choiceofmultiplechoicequestion',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is_active'),
        ),
        migrations.AlterField(
            model_name='choiceofmultiplechoicequestion',
            name='is_true',
            field=models.BooleanField(default=False, verbose_name='is_true'),
        ),
        migrations.AlterField(
            model_name='choiceofmultiplechoicequestion',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, verbose_name='modified_date'),
        ),
        migrations.AlterField(
            model_name='choiceofmultiplechoicequestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exam.question', verbose_name='question'),
        ),
        migrations.AlterField(
            model_name='descriptiveanswer',
            name='answer',
            field=models.TextField(verbose_name='answer'),
        ),
        migrations.AlterField(
            model_name='descriptiveanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exam.question', verbose_name='question'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_date'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is_active'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, verbose_name='modified_date'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='questions',
            field=models.ManyToManyField(to='exam.question', verbose_name='questions'),
        ),
        migrations.AlterField(
            model_name='fileanswer',
            name='answer',
            field=models.FileField(upload_to='', verbose_name='answer'),
        ),
        migrations.AlterField(
            model_name='fileanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exam.question', verbose_name='question'),
        ),
        migrations.AlterField(
            model_name='multiplechoiceanswer',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exam.choiceofmultiplechoicequestion', verbose_name='answer'),
        ),
        migrations.AlterField(
            model_name='multiplechoiceanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exam.question', verbose_name='question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_date'),
        ),
        migrations.AlterField(
            model_name='question',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is_active'),
        ),
        migrations.AlterField(
            model_name='question',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, verbose_name='modified_date'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(verbose_name='question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('MultipleChoice', 'MultipleChoice'), ('Drop Down', 'Drop Down'), ('File', 'File'), ('Descriptive', 'Descriptive')], default='Descriptive', max_length=20, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='userexam',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exam.exam', verbose_name='exam'),
        ),
        migrations.AlterField(
            model_name='userexam',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
