# Generated by Django 4.1.3 on 2023-04-04 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_alter_choiceofmultiplechoicequestion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='choiceofmultiplechoicequestion',
            name='choice_en',
            field=models.CharField(max_length=200, null=True, verbose_name='choice'),
        ),
        migrations.AddField(
            model_name='choiceofmultiplechoicequestion',
            name='choice_fa',
            field=models.CharField(max_length=200, null=True, verbose_name='choice'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_en',
            field=models.TextField(null=True, verbose_name='question'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_fa',
            field=models.TextField(null=True, verbose_name='question'),
        ),
    ]
