# Generated by Django 4.1.3 on 2023-02-01 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='مبلغ')),
                ('ref_id', models.CharField(blank=True, max_length=512, null=True, verbose_name='شماره تراکنش')),
                ('status', models.CharField(choices=[('S', 'موفق'), ('U', 'ناموفق'), ('C', 'لغو شده'), ('A', 'در انتظار پرداخت')], default='در انتظار پرداخت', max_length=20, verbose_name='وضعیت')),
                ('authority', models.CharField(blank=True, max_length=512, null=True, verbose_name='شناسه مرجع')),
                ('link', models.URLField(blank=True, null=True, verbose_name='لینک درگاه پرداخت')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت ها',
                'ordering': ('created_date',),
            },
        ),
    ]
