# Generated by Django 4.1.3 on 2023-05-16 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGateWay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created_date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='modified_date')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='title')),
                ('title_fa', models.CharField(max_length=200, null=True, verbose_name='title')),
                ('icon', models.FileField(upload_to='payment-icons', verbose_name='icon')),
                ('request_url', models.CharField(max_length=500, verbose_name='request_url')),
                ('verify_url', models.CharField(max_length=500, verbose_name='verify_url')),
                ('startpay_url', models.CharField(max_length=500, verbose_name='startpay_url')),
                ('merchant', models.CharField(max_length=200, verbose_name='merchant')),
            ],
            options={
                'verbose_name': 'Payment GateWay',
                'verbose_name_plural': 'Payment GateWays',
            },
        ),
        migrations.CreateModel(
            name='PaymentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created_date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='modified_date')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
                ('status', models.CharField(max_length=200, verbose_name='status')),
                ('status_en', models.CharField(max_length=200, null=True, verbose_name='status')),
                ('status_fa', models.CharField(max_length=200, null=True, verbose_name='status')),
            ],
            options={
                'verbose_name': 'Payment Status',
                'verbose_name_plural': 'Payment Statuses',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='amount')),
                ('ref_id', models.CharField(blank=True, max_length=512, null=True, verbose_name='ref_id')),
                ('authority', models.CharField(blank=True, max_length=512, null=True, verbose_name='authority')),
                ('link', models.URLField(blank=True, null=True, verbose_name='link')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created_date')),
                ('payment_gateway', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.paymentgateway', verbose_name='payment_gateway')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.paymentstatus', verbose_name='status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ('created_date',),
            },
        ),
    ]
