# Generated by Django 4.1.3 on 2023-04-04 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created_date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='modified_date')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
                ('status', models.CharField(max_length=200, verbose_name='status')),
            ],
            options={
                'verbose_name': 'Payment Status',
                'verbose_name_plural': 'Payment Statuses',
            },
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ('created_date',), 'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.PositiveIntegerField(verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='authority',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='authority'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_date'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='link'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='ref_id',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='ref_id'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.paymentstatus', verbose_name='status'),
        ),
    ]
