# Generated by Django 4.1.3 on 2023-04-04 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_paymentstatus_alter_payment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentstatus',
            name='status_en',
            field=models.CharField(max_length=200, null=True, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='paymentstatus',
            name='status_fa',
            field=models.CharField(max_length=200, null=True, verbose_name='status'),
        ),
    ]
