# Generated by Django 4.1.3 on 2023-04-04 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticketing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagefile',
            options={'verbose_name': 'File', 'verbose_name_plural': 'Files'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name': 'Ticket', 'verbose_name_plural': 'Tickets'},
        ),
        migrations.AlterModelOptions(
            name='ticketdepartment',
            options={'verbose_name': 'Department', 'verbose_name_plural': 'Departments'},
        ),
        migrations.AlterModelOptions(
            name='ticketmessage',
            options={'verbose_name': 'Messages', 'verbose_name_plural': 'Messageses'},
        ),
        migrations.AlterModelOptions(
            name='ticketpriority',
            options={'verbose_name': 'Priority', 'verbose_name_plural': 'Priorities'},
        ),
        migrations.AlterModelOptions(
            name='ticketstatus',
            options={'verbose_name': 'Status', 'verbose_name_plural': 'Statuses'},
        ),
        migrations.AlterField(
            model_name='messagefile',
            name='file',
            field=models.FileField(upload_to='', verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='messagefile',
            name='message',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ticketing.ticketmessage', verbose_name='message'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='client'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_date'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticketing.ticketdepartment', verbose_name='department'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='is_archive',
            field=models.BooleanField(default=False, verbose_name='is_archive'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, verbose_name='modified_date'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticketing.ticketpriority', verbose_name='priority'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticketing.ticketstatus', verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='subject',
            field=models.CharField(max_length=200, verbose_name='subject'),
        ),
        migrations.AlterField(
            model_name='ticketdepartment',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_date'),
        ),
        migrations.AlterField(
            model_name='ticketdepartment',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is_active'),
        ),
        migrations.AlterField(
            model_name='ticketdepartment',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, verbose_name='modified_date'),
        ),
        migrations.AlterField(
            model_name='ticketdepartment',
            name='name',
            field=models.CharField(max_length=200, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='ticketmessage',
            name='content',
            field=models.TextField(verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='ticketmessage',
            name='ticket',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ticketing.ticket', verbose_name='ticket'),
        ),
        migrations.AlterField(
            model_name='ticketmessage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='ticketpriority',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_date'),
        ),
        migrations.AlterField(
            model_name='ticketpriority',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is_active'),
        ),
        migrations.AlterField(
            model_name='ticketpriority',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, verbose_name='modified_date'),
        ),
        migrations.AlterField(
            model_name='ticketpriority',
            name='title',
            field=models.CharField(max_length=200, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='ticketstatus',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_date'),
        ),
        migrations.AlterField(
            model_name='ticketstatus',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is_active'),
        ),
        migrations.AlterField(
            model_name='ticketstatus',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, verbose_name='modified_date'),
        ),
        migrations.AlterField(
            model_name='ticketstatus',
            name='title',
            field=models.CharField(max_length=200, verbose_name='title'),
        ),
    ]
