# Generated by Django 4.1.3 on 2024-12-21 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0003_ticketdepartment_name_en_ticketdepartment_name_fa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagefile',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketing.ticketmessage', verbose_name='message'),
        ),
        migrations.AlterField(
            model_name='ticketmessage',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketing.ticket', verbose_name='ticket'),
        ),
    ]
