# Generated by Django 4.1.3 on 2023-04-04 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletters',
            options={'verbose_name': 'NewsLetters', 'verbose_name_plural': 'NewsLetters'},
        ),
        migrations.AlterField(
            model_name='newsletters',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email'),
        ),
    ]
