# Generated by Django 4.1.3 on 2022-12-25 07:59

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_city_address_related_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='national_id',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[accounts.validators.validate_national_code], verbose_name='کد ملی'),
        ),
    ]
