# Generated by Django 4.1.3 on 2023-05-16 15:28

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created_date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='modified_date')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='title')),
                ('title_fa', models.CharField(max_length=200, null=True, verbose_name='title')),
                ('object_id', models.PositiveIntegerField()),
                ('minimum_score', models.PositiveIntegerField(verbose_name='minimum_score')),
                ('duration', models.DurationField(verbose_name='duration')),
                ('wrong_questions_weight', models.PositiveIntegerField(default=3, verbose_name='wrong_questions_weight')),
                ('correct_questions_weight', models.PositiveIntegerField(default=1, verbose_name='correct_questions_weight')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='exams.exam', verbose_name='parent')),
            ],
            options={
                'verbose_name': 'Exam',
                'verbose_name_plural': 'Exams',
                'ordering': ('created_date', 'title'),
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created_date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='modified_date')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='title')),
                ('question', models.TextField(verbose_name='question')),
                ('question_en', models.TextField(null=True, verbose_name='question')),
                ('question_fa', models.TextField(null=True, verbose_name='question')),
                ('choice_one', models.TextField(verbose_name='choice_one')),
                ('choice_one_en', models.TextField(null=True, verbose_name='choice_one')),
                ('choice_one_fa', models.TextField(null=True, verbose_name='choice_one')),
                ('choice_two', models.TextField(verbose_name='choice_two')),
                ('choice_two_en', models.TextField(null=True, verbose_name='choice_two')),
                ('choice_two_fa', models.TextField(null=True, verbose_name='choice_two')),
                ('choice_three', models.TextField(verbose_name='choice_three')),
                ('choice_three_en', models.TextField(null=True, verbose_name='choice_three')),
                ('choice_three_fa', models.TextField(null=True, verbose_name='choice_three')),
                ('choice_four', models.TextField(verbose_name='choice_four')),
                ('choice_four_en', models.TextField(null=True, verbose_name='choice_four')),
                ('choice_four_fa', models.TextField(null=True, verbose_name='choice_four')),
                ('correct_answer', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], verbose_name='correct_answer')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exams.exam', verbose_name='exam')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
            },
        ),
        migrations.CreateModel(
            name='UserQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created_date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='modified_date')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
                ('answer', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], verbose_name='answer')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exams.exam', verbose_name='exam')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exams.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'User Question',
                'verbose_name_plural': 'User Questions',
            },
        ),
        migrations.CreateModel(
            name='UserExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created_date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='modified_date')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exams.exam', verbose_name='exam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'User Exam',
                'verbose_name_plural': 'User Exams',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created_date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='modified_date')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
                ('no_all_questions', models.PositiveIntegerField(verbose_name='no_all_questions')),
                ('no_wrong_questions', models.PositiveIntegerField(verbose_name='no_wrong_questions')),
                ('no_correct_questions', models.PositiveIntegerField(verbose_name='no_correct_questions')),
                ('max_score', models.FloatField(default=0, verbose_name='max_score')),
                ('score', models.FloatField(default=0, verbose_name='score')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.exam', verbose_name='exam')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='exams.result', verbose_name='parent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Result',
                'verbose_name_plural': 'Results',
            },
        ),
        migrations.CreateModel(
            name='DescriptiveAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created_date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='modified_date')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='content')),
                ('content_en', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='content')),
                ('content_fa', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='content')),
                ('exam', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='exams.exam', verbose_name='exam')),
            ],
            options={
                'verbose_name': 'Descriptive Answer',
                'verbose_name_plural': 'Descriptive Answers',
            },
        ),
    ]
