# Generated by Django 4.1.3 on 2023-05-26 15:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserQuestion',
            new_name='UserAnswer',
        ),
        migrations.AlterModelOptions(
            name='useranswer',
            options={'verbose_name': 'User Answer', 'verbose_name_plural': 'User Answers'},
        ),
    ]
