# Generated by Django 4.1.3 on 2023-02-28 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatedpost',
            name='related_posts',
            field=models.ManyToManyField(null=True, to='blog.post', verbose_name='پست'),
        ),
    ]
