# Generated by Django 4.1.3 on 2023-03-01 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_relatedpost_related_posts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='avater',
            new_name='avatar',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='avater_alt',
            new_name='avatar_alt',
        ),
    ]
