# Generated by Django 4.1.3 on 2023-05-16 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_author_about_en_author_about_fa_category_title_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.FileField(upload_to='post-images', verbose_name='thumbnail'),
        ),
    ]
