# Generated by Django 4.1.3 on 2023-05-25 17:17

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='schema',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='schema'),
            preserve_default=False,
        ),
    ]
