# Generated by Django 4.1.3 on 2023-05-16 15:51

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created_date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='modified_date')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='title')),
                ('title_fa', models.CharField(max_length=200, null=True, verbose_name='title')),
                ('image', models.FileField(upload_to='chapter-images')),
                ('image_alt', models.CharField(blank=True, max_length=200, null=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='description')),
                ('description_en', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='description')),
                ('description_fa', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='description')),
                ('price', models.PositiveIntegerField(verbose_name='price')),
                ('for_sale', models.BooleanField(default=True, verbose_name='for_sale')),
            ],
            options={
                'verbose_name': 'Chapter',
                'verbose_name_plural': 'Chapters',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created_date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='modified_date')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='title')),
                ('title_fa', models.CharField(max_length=200, null=True, verbose_name='title')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.FileField(upload_to='course-images', verbose_name='image')),
                ('image_alt', models.CharField(blank=True, max_length=200, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='course-videos', verbose_name='video')),
                ('cover', models.FileField(blank=True, null=True, upload_to='course-covers', verbose_name='cover')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='description')),
                ('description_en', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='description')),
                ('description_fa', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='description')),
                ('price', models.PositiveIntegerField(verbose_name='price')),
                ('for_sale', models.BooleanField(default=True, verbose_name='for_sale')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created_date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='modified_date')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='title')),
                ('title_fa', models.CharField(max_length=200, null=True, verbose_name='title')),
                ('icon', models.FileField(blank=True, null=True, upload_to='product-category-icon', verbose_name='icon')),
                ('image_alt', models.CharField(blank=True, max_length=200, null=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='description')),
                ('description_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='description')),
                ('description_fa', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='description')),
                ('show_on_home_page', models.BooleanField(default=False, verbose_name='show_on_home_page')),
                ('meta_title', models.CharField(blank=True, max_length=128, null=True, verbose_name='meta_title')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='meta_description')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created_date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='modified_date')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='title')),
                ('title_fa', models.CharField(max_length=200, null=True, verbose_name='title')),
                ('price', models.PositiveIntegerField(verbose_name='price')),
                ('image', models.FileField(upload_to='note-images')),
                ('image_alt', models.CharField(blank=True, max_length=200, null=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='content')),
                ('for_sale', models.BooleanField(default=True, verbose_name='for_sale')),
                ('show_on_home_page', models.BooleanField(default=False, verbose_name='show_on_home_page')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.chapter', verbose_name='chapter')),
                ('participants', models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL, verbose_name='participants')),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created_date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='modified_date')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
            },
        ),
        migrations.CreateModel(
            name='NoteTaking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='content')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.note', verbose_name='note')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Note Taking',
                'verbose_name_plural': 'Note Taking',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created_date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='modified_date')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='title')),
                ('title_fa', models.CharField(max_length=200, null=True, verbose_name='title')),
                ('image', models.FileField(upload_to='lesson-images')),
                ('image_alt', models.CharField(blank=True, max_length=200, null=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='description')),
                ('description_en', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='description')),
                ('description_fa', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='description')),
                ('price', models.PositiveIntegerField(verbose_name='price')),
                ('for_sale', models.BooleanField(default=True, verbose_name='for_sale')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='course')),
            ],
            options={
                'verbose_name': 'Lesson',
                'verbose_name_plural': 'Lessons',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.coursecategory', verbose_name='category'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.teacher', verbose_name='teacher'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.lesson', verbose_name='lesson'),
        ),
    ]
