# Generated by Django 4.1.3 on 2023-04-04 09:55

import ckeditor_uploader.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': 'About Us', 'verbose_name_plural': 'About Us'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['name'], 'verbose_name': 'City', 'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='component',
            options={'ordering': ['order'], 'verbose_name': 'Component', 'verbose_name_plural': 'Components'},
        ),
        migrations.AlterModelOptions(
            name='componentitem',
            options={'verbose_name': 'Component Item', 'verbose_name_plural': 'Component Items'},
        ),
        migrations.AlterModelOptions(
            name='contactusdetail',
            options={'verbose_name': 'Contact Us Detail', 'verbose_name_plural': 'Contact Us Detail'},
        ),
        migrations.AlterModelOptions(
            name='contactusform',
            options={'verbose_name': 'Contact Us Form', 'verbose_name_plural': 'Contact Us Forms'},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': 'FAQ', 'verbose_name_plural': 'FAQs'},
        ),
        migrations.AlterModelOptions(
            name='footer',
            options={'verbose_name': 'Footer', 'verbose_name_plural': 'Footers'},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ('order',), 'verbose_name': 'Menu', 'verbose_name_plural': 'Menus'},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name': 'Page', 'verbose_name_plural': 'Pages'},
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'ordering': ('order',), 'verbose_name': 'Slider', 'verbose_name_plural': 'Sliders'},
        ),
        migrations.AlterModelOptions(
            name='socialaccount',
            options={'verbose_name': 'Social Account', 'verbose_name_plural': 'Social Accounts'},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'ordering': ['name'], 'verbose_name': 'State', 'verbose_name_plural': 'States'},
        ),
        migrations.AlterModelOptions(
            name='termsandconditions',
            options={'verbose_name': 'Terms And Conditions', 'verbose_name_plural': 'Terms And Conditions'},
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_date'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is_active'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, verbose_name='modified_date'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='city',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_date'),
        ),
        migrations.AlterField(
            model_name='city',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is_active'),
        ),
        migrations.AlterField(
            model_name='city',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, verbose_name='modified_date'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=256, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.state', verbose_name='state'),
        ),
        migrations.AlterField(
            model_name='component',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_date'),
        ),
        migrations.AlterField(
            model_name='component',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is_active'),
        ),
        migrations.AlterField(
            model_name='component',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, verbose_name='modified_date'),
        ),
        migrations.AlterField(
            model_name='component',
            name='name',
            field=models.CharField(max_length=200, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='component',
            name='order',
            field=models.IntegerField(default=1, verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='component',
            name='page',
            field=models.ManyToManyField(to='base.page', verbose_name='page'),
        ),
        migrations.AlterField(
            model_name='component',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='base.component', verbose_name='parent'),
        ),
        migrations.AlterField(
            model_name='componentitem',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.component', verbose_name='component'),
        ),
        migrations.AlterField(
            model_name='componentitem',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='componentitem',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_date'),
        ),
        migrations.AlterField(
            model_name='componentitem',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='component', verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='componentitem',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is_active'),
        ),
        migrations.AlterField(
            model_name='componentitem',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, verbose_name='modified_date'),
        ),
        migrations.AlterField(
            model_name='componentitem',
            name='type',
            field=models.CharField(choices=[('File', 'File'), ('Text', 'Text')], max_length=20, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='contactusdetail',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_date'),
        ),
        migrations.AlterField(
            model_name='contactusdetail',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='contactusdetail',
            name='image',
            field=models.ImageField(upload_to='contact_us', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='contactusdetail',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is_active'),
        ),
        migrations.AlterField(
            model_name='contactusdetail',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, verbose_name='modified_date'),
        ),
        migrations.AlterField(
            model_name='contactusdetail',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='phone_number'),
        ),
        migrations.AlterField(
            model_name='contactusdetail',
            name='social_accounts',
            field=models.ManyToManyField(to='base.socialaccount', verbose_name='social_accounts'),
        ),
        migrations.AlterField(
            model_name='contactusform',
            name='cell_phone_number',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Start with 09/9 and it must 9 digits after that. For example: 09120000000 or 9120000000', regex='^(09|9)\\d{9}$')], verbose_name='cell_phone_number'),
        ),
        migrations.AlterField(
            model_name='contactusform',
            name='full_name',
            field=models.CharField(max_length=200, verbose_name='full_name'),
        ),
        migrations.AlterField(
            model_name='contactusform',
            name='message',
            field=models.TextField(verbose_name='message'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(verbose_name='answer'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_date'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is_active'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, verbose_name='modified_date'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.CharField(max_length=500, verbose_name='question'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='contact_us',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.contactusdetail', verbose_name='contact_us'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='content',
            field=models.TextField(verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_date'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is_active'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='logo',
            field=models.FileField(upload_to='footer', verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, verbose_name='modified_date'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='social_accounts',
            field=models.ManyToManyField(to='base.socialaccount', verbose_name='social_accounts'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='useful_link',
            field=models.ManyToManyField(to='base.page', verbose_name='useful_link'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_date'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='menus', verbose_name='icon'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is_active'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, verbose_name='modified_date'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='order',
            field=models.IntegerField(default=1, verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.page', verbose_name='page'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='base.menu', verbose_name='parent'),
        ),
        migrations.AlterField(
            model_name='page',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_date'),
        ),
        migrations.AlterField(
            model_name='page',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is_active'),
        ),
        migrations.AlterField(
            model_name='page',
            name='link',
            field=models.CharField(max_length=500, verbose_name='link'),
        ),
        migrations.AlterField(
            model_name='page',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, verbose_name='modified_date'),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(max_length=200, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_date'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.FileField(upload_to='slider', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is_active'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='link',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='link'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, verbose_name='modified_date'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='order',
            field=models.IntegerField(default=1, verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.page', verbose_name='page'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='text',
            field=models.TextField(verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='title',
            field=models.CharField(max_length=200, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_date'),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is_active'),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='link',
            field=models.CharField(max_length=500, verbose_name='link'),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='logo',
            field=models.ImageField(upload_to='social_accounts', verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, verbose_name='modified_date'),
        ),
        migrations.AlterField(
            model_name='state',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_date'),
        ),
        migrations.AlterField(
            model_name='state',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is_active'),
        ),
        migrations.AlterField(
            model_name='state',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, verbose_name='modified_date'),
        ),
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(max_length=200, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='termsandconditions',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_date'),
        ),
        migrations.AlterField(
            model_name='termsandconditions',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is_active'),
        ),
        migrations.AlterField(
            model_name='termsandconditions',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, verbose_name='modified_date'),
        ),
        migrations.AlterField(
            model_name='termsandconditions',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='text'),
        ),
    ]
