# Generated by Django 4.1.3 on 2022-12-19 06:39

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_state_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsAndConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='زمان بروز رسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='محتوا')),
            ],
            options={
                'verbose_name': 'قوانین و مقررات',
                'verbose_name_plural': 'قوانین و مقررات',
            },
        ),
    ]
