# Generated by Django 4.1.3 on 2022-12-19 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_termsandconditions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='menus', verbose_name='آیکون'),
        ),
    ]
