# Generated by Django 4.1.3 on 2023-02-01 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='زمان بروز رسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('title', models.CharField(max_length=200, verbose_name='تایتل')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('delivery_price', models.PositiveIntegerField(default=0, verbose_name='هزینه ارسال')),
            ],
            options={
                'verbose_name': 'نوع ارسال',
                'verbose_name_plural': 'انواع ارسال',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code', models.CharField(blank=True, max_length=200, null=True, verbose_name='کد تخفیف')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='مبلغ')),
                ('discount_amount', models.PositiveIntegerField(default=0, verbose_name='مبلغ تخفیف')),
                ('status', models.CharField(choices=[('درانتظار پرداخت', 'درانتظار پرداخت'), ('پرداخت شده', 'پرداخت شده'), ('ارسال شده', 'ارسال شده')], default='درانتظار پرداخت', max_length=20, verbose_name='وضعیت')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.address', verbose_name='آدرس')),
                ('delivery_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.deliverytype', verbose_name='نوع ارسال')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='payments.payment', verbose_name='پرداخت')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارشات',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='تعداد')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='سفارش')),
                ('product_quantity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.productquantity', verbose_name='کالا')),
            ],
            options={
                'verbose_name': 'کالای سفارش',
                'verbose_name_plural': 'کالا های سفارش',
            },
        ),
    ]
