# Generated by Django 4.1.3 on 2023-01-20 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orderproductquantity_related_product_quantity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='زمان بروز رسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('title', models.CharField(max_length=200, verbose_name='تایتل')),
                ('icon', models.FileField(blank=True, null=True, upload_to='product_brand_icon', verbose_name='آیکون')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.brand', verbose_name='برند والد')),
            ],
            options={
                'verbose_name': 'برند',
                'verbose_name_plural': 'برند ها',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='زمان بروز رسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('title', models.CharField(max_length=200, verbose_name='تایتل')),
                ('icon', models.FileField(blank=True, null=True, upload_to='product_category_icon', verbose_name='آیکون')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.category', verbose_name='دسته بندی والد')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('full_name', models.CharField(max_length=200, verbose_name='نام و نام خانوادگی')),
                ('content', models.TextField(verbose_name='متن')),
                ('rate', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, verbose_name='امتیاز')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('is_accepted', models.BooleanField(default=False, verbose_name='تایید شده')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='products.comment', verbose_name='کامنت والد')),
            ],
            options={
                'verbose_name': 'کامنت پست',
                'verbose_name_plural': 'کامنت های پست',
                'ordering': ('created_date',),
            },
        ),
        migrations.CreateModel(
            name='ProductAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=200, verbose_name='مقدار')),
            ],
            options={
                'verbose_name': 'مقدار ویژگی محصول',
                'verbose_name_plural': 'مقادیر ویژگی محصول',
            },
        ),
        migrations.CreateModel(
            name='ProductBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='زمان بروز رسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('brand', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.brand', verbose_name='برند')),
            ],
            options={
                'verbose_name': 'برند محصول',
                'verbose_name_plural': 'برند های محصولات',
            },
        ),
        migrations.CreateModel(
            name='ProductComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='زمان بروز رسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('comment', models.ManyToManyField(to='products.comment', verbose_name='کامنت')),
            ],
            options={
                'verbose_name': 'کامنت محصول',
                'verbose_name_plural': 'کامنت های محصولات',
            },
        ),
        migrations.CreateModel(
            name='ProductStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='زمان بروز رسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'انبار محصولات',
                'verbose_name_plural': 'انبار های محصولات',
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='زمان بروز رسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('title', models.CharField(max_length=200, verbose_name='تایتل')),
            ],
            options={
                'verbose_name': 'نوع محصول',
                'verbose_name_plural': 'انواع محصولات',
            },
        ),
        migrations.CreateModel(
            name='RelatedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='زمان بروز رسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'محصول مرتبط',
                'verbose_name_plural': 'محصول های مرتبط',
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='زمان بروز رسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'فروشنده',
                'verbose_name_plural': 'فروشنده ها',
            },
        ),
        migrations.CreateModel(
            name='SellerStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='زمان بروز رسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.seller', verbose_name='فروشنده')),
            ],
            options={
                'verbose_name': 'انبار فروشنده',
                'verbose_name_plural': 'انبار های فروشنده',
            },
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='زمان بروز رسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('qty', models.PositiveIntegerField(verbose_name='موجودی')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت')),
            ],
            options={
                'verbose_name': 'انبار',
                'verbose_name_plural': 'انبار ها',
            },
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='related_product',
        ),
        migrations.RemoveField(
            model_name='productquantity',
            name='related_product',
        ),
        migrations.RemoveField(
            model_name='productquantity',
            name='related_product_attribute',
        ),
        migrations.RemoveField(
            model_name='review',
            name='related_product',
        ),
        migrations.RemoveField(
            model_name='review',
            name='related_review',
        ),
        migrations.RemoveField(
            model_name='review',
            name='related_user',
        ),
        migrations.RemoveField(
            model_name='product',
            name='related_product_category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='related_products',
        ),
        migrations.RemoveField(
            model_name='productattribute',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='productattribute',
            name='description',
        ),
        migrations.RemoveField(
            model_name='productattribute',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='productattribute',
            name='modified_date',
        ),
        migrations.RemoveField(
            model_name='productattribute',
            name='related_product',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='title',
        ),
        migrations.AddField(
            model_name='product',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='کالای پدر'),
        ),
        migrations.AddField(
            model_name='product',
            name='upc',
            field=models.CharField(default='', max_length=200, verbose_name='شناسه محصول'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productcategory',
            name='product',
            field=models.ManyToManyField(to='products.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='ProductCatalog',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
        migrations.DeleteModel(
            name='ProductQuantity',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.AddField(
            model_name='sellerstorage',
            name='storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.storage', verbose_name='انبار'),
        ),
        migrations.AddField(
            model_name='relatedproduct',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='محصول'),
        ),
        migrations.AddField(
            model_name='relatedproduct',
            name='related_product',
            field=models.ManyToManyField(related_name='related_products', to='products.product', verbose_name='محصولات'),
        ),
        migrations.AddField(
            model_name='productstorage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='محصول'),
        ),
        migrations.AddField(
            model_name='productstorage',
            name='storage',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.storage', verbose_name='انبار'),
        ),
        migrations.AddField(
            model_name='productcomment',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='محصول'),
        ),
        migrations.AddField(
            model_name='productbrand',
            name='product',
            field=models.ManyToManyField(to='products.product', verbose_name='محصول'),
        ),
        migrations.AddField(
            model_name='productattributevalue',
            name='product',
            field=models.ManyToManyField(to='products.product', verbose_name='محصولات'),
        ),
        migrations.AddField(
            model_name='productattributevalue',
            name='product_attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productattribute', verbose_name='دسته بندی ویژگی'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='products.producttype', verbose_name='نوع محصول'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productattribute',
            name='product_type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='products.producttype', verbose_name='نوع محصول'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productcategory',
            name='category',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='products.category', verbose_name='دسته بندی'),
            preserve_default=False,
        ),
    ]
