# Generated by Django 4.1.3 on 2023-01-20 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_brand_category_comment_productattributevalue_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattributevalue',
            name='product',
        ),
        migrations.AddField(
            model_name='productattributevalue',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='محصولات'),
            preserve_default=False,
        ),
    ]
